/*
 * Unofficial API for Ray.So that turns your code into beautiful images.
 * Choose from a range of syntax colors, hide or show the background, and
 * toggle between a dark and light window.
 *
 * Source: ray.so
 * Author: github.com/s0ftik3
 */

export const CardTheme = {
  VERCEL: "vercel",
  SUPABASE: "supabase",
  TAILWIND: "tailwind",
  OPENAI: "openai",
  MINTLIFY: "mintlify",
  PRISMA: "prisma",
  CLERK: "clerk",
  BITMAP: "bitmap",
  NOIR: "noir",
  ICE: "ice",
  SAND: "sand",
  FOREST: "forest",
  MONO: "mono",
  BREEZE: "breeze",
  CANDY: "candy",
  CRIMSON: "crimson",
  FALCON: "falcon",
  MEADOW: "meadow",
  MIDNIGHT: "midnight",
  RAINDROP: "raindrop",
  SUNSET: "sunset",
};

export const CardPadding = {
  sm: 16,
  md: 32,
  lg: 64,
  xl: 128,
};

export const CardProgrammingLanguage = {
  SHELL: "shell",
  ASTRO: "astro",
  CPP: "cpp",
  CSHARP: "csharp",
  CLOJURE: "clojure",
  CRYSTAL: "crystal",
  CSS: "css",
  DART: "dart",
  DIFF: "diff",
  DOCKERFILE: "dockerfile",
  ELM: "elm",
  ERB: "erb",
  ELIXIR: "elixir",
  ERLANG: "erlang",
  GLEAM: "gleam",
  GRAPHQL: "graphql",
  GO: "go",
  HASKELL: "haskell",
  HTML: "html",
  JAVA: "java",
  JAVASCRIPT: "javascript",
  JULIA: "julia",
  JSON: "json",
  JSX: "jsx",
  KOTLIN: "kotlin",
  LATEX: "latex",
  LISP: "lisp",
  LUA: "lua",
  MARKDOWN: "markdown",
  MATLAB: "matlab",
  MOVE: "move",
  PLAINTEXT: "plaintext",
  POWERSHELL: "powershell",
  OBJECTIVEC: "objectivec",
  OCAML: "ocaml",
  PHP: "php",
  PRISMA: "prisma",
  PYTHON: "python",
  R: "r",
  RUBY: "ruby",
  RUST: "rust",
  SCALA: "scala",
  SCSS: "scss",
  SOLIDITY: "solidity",
  SQL: "sql",
  SWIFT: "swift",
  SVELTE: "svelte",
  TOML: "toml",
  TYPESCRIPT: "typescript",
  TSX: "tsx",
  VUE: "vue",
  XML: "xml",
  YAML: "yaml",
  ZIG: "zig",
};
